[include]
files = /etc/supervisor/common.conf

[program:octane]
command=php /var/www/html/artisan octane:frankenphp --watch --port=80 --caddyfile=/etc/caddy/Caddyfile
autostart=true
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true

[program:vite]
command=npm run dev
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/vite.log
stderr_logfile=/var/log/supervisor/vite-error.log
environment=NODE_ENV="development"

[program:nutgram]
command=php /var/www/html/artisan nutgram:listen
directory=/var/www/html
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nutgram.log
stderr_logfile=/var/log/supervisor/nutgram-error.log